# Generated by Django 4.1.3 on 2023-08-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listing_type', models.CharField(choices=[('Rent', 'Rent'), ('Sell', 'Sell')], default='Sell', max_length=50)),
                ('City', models.CharField(choices=[('Gwalior', 'Gwalior'), ('Indore', 'Indore'), ('Bhopal', 'Bhopal'), ('Jablpur', 'Jablpur')], default='Bhopal', max_length=10)),
                ('Ownername', models.CharField(default=None, max_length=25)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Address', models.CharField(default='', max_length=60)),
                ('Pincode', models.IntegerField(default=0)),
                ('Contactnumber', models.ImageField(default=0, max_length=12, upload_to='')),
                ('Image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/')),
                ('Room_var', models.CharField(choices=[('4BHK', '4BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('Single+Kitchen', 'Single+Kitchen'), ('SingleRoom', 'SingleRoom'), ('1BHK', '1BHK')], default=None, max_length=20)),
                ('Price', models.IntegerField(default=0)),
                ('Area', models.IntegerField(default=0)),
                ('Bath_room', models.IntegerField(default=0)),
                ('Room_description', models.CharField(default='', max_length=100)),
                ('Number_of_rooms', models.IntegerField(default=0)),
                ('Propert_age', models.IntegerField(default=0)),
            ],
        ),
    ]
