# Generated by Django 4.1.3 on 2023-08-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Bhopal', 'Bhopal'), ('Gwalior', 'Gwalior'), ('Indore', 'Indore'), ('Jablpur', 'Jablpur')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Listing_type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], default='Sell', max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('2BHK', '2BHK'), ('Single+Kitchen', 'Single+Kitchen'), ('3BHK', '3BHK'), ('1BHK', '1BHK'), ('SingleRoom', 'SingleRoom'), ('4BHK', '4BHK')], default=None, max_length=20),
        ),
    ]
