# Generated by Django 4.1.3 on 2023-08-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0002_alter_detail_city_alter_detail_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Latitude',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='detail',
            name='Longitude',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Jablpur', 'Jablpur'), ('Indore', 'Indore'), ('Bhopal', 'Bhopal'), ('Gwalior', 'Gwalior')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('3BHK', '3BHK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('SingleRoom', 'SingleRoom'), ('4BHK', '4BHK'), ('Single+Kitchen', 'Single+Kitchen')], default=None, max_length=20),
        ),
    ]
