# Generated by Django 4.1.3 on 2023-09-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0004_alter_detail_city_alter_detail_contactnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Gwalior', 'Gwalior'), ('Bhopal', 'Bhopal'), ('Indore', 'Indore'), ('Jablpur', 'Jablpur')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Listing_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sell', 'Sell')], default='Sell', max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('Single+Kitchen', 'Single+Kitchen'), ('4BHK', '4BHK'), ('3BHK', '3BHK'), ('1BHK', '1BHK'), ('SingleRoom', 'SingleRoom'), ('2BHK', '2BHK')], default=None, max_length=20),
        ),
    ]
