# Generated by Django 4.1.3 on 2023-09-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0006_alter_detail_city_alter_detail_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Indore', 'Indore'), ('Jablpur', 'Jablpur'), ('Bhopal', 'Bhopal'), ('Gwalior', 'Gwalior')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Listing_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sell', 'Sell')], default='Sell', max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('2BHK', '2BHK'), ('Single+Kitchen', 'Single+Kitchen'), ('SingleRoom', 'SingleRoom'), ('1BHK', '1BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK')], default=None, max_length=20),
        ),
    ]
