# Generated by Django 4.1.3 on 2023-09-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0007_alter_detail_city_alter_detail_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Gwalior', 'Gwalior'), ('Indore', 'Indore'), ('Bhopal', 'Bhopal'), ('Jablpur', 'Jablpur')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('4BHK', '4BHK'), ('Single+Kitchen', 'Single+Kitchen'), ('SingleRoom', 'SingleRoom'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('1BHK', '1BHK')], default=None, max_length=20),
        ),
    ]
