# Generated by Django 4.1.3 on 2023-09-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0008_alter_detail_city_alter_detail_room_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Area',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Bhopal', 'Bhopal'), ('Indore', 'Indore'), ('Jablpur', 'Jablpur'), ('Gwalior', 'Gwalior')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Listing_type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], default='Sell', max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Propert_age',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('3BHK', '3BHK'), ('1BHK', '1BHK'), ('SingleRoom', 'SingleRoom'), ('2BHK', '2BHK'), ('4BHK', '4BHK'), ('Single+Kitchen', 'Single+Kitchen')], default=None, max_length=20),
        ),
    ]
