# Generated by Django 4.1.3 on 2023-09-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0009_alter_detail_area_alter_detail_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Jablpur', 'Jablpur'), ('Bhopal', 'Bhopal'), ('Gwalior', 'Gwalior'), ('Indore', 'Indore')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Listing_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sell', 'Sell')], default='Sell', max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('3BHK', '3BHK'), ('2BHK', '2BHK'), ('SingleRoom', 'SingleRoom'), ('4BHK', '4BHK'), ('Single+Kitchen', 'Single+Kitchen'), ('1BHK', '1BHK')], default=None, max_length=20),
        ),
    ]
