# Generated by Django 4.1.3 on 2023-09-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0010_alter_detail_city_alter_detail_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Jablpur', 'Jablpur'), ('Bhopal', 'Bhopal'), ('Indore', 'Indore'), ('Gwalior', 'Gwalior')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('SingleRoom', 'SingleRoom'), ('3BHK', '3BHK'), ('2BHK', '2BHK'), ('Single+Kitchen', 'Single+Kitchen'), ('1BHK', '1BHK'), ('4BHK', '4BHK')], default=None, max_length=20),
        ),
    ]
