# Generated by Django 4.1.3 on 2023-09-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0011_alter_detail_city_alter_detail_room_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Bhopal', 'Bhopal'), ('Jablpur', 'Jablpur'), ('Indore', 'Indore'), ('Gwalior', 'Gwalior')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('Single+Kitchen', 'Single+Kitchen'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('SingleRoom', 'SingleRoom')], default=None, max_length=20),
        ),
    ]
