# Generated by Django 4.1.3 on 2023-09-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0012_alter_detail_city_alter_detail_room_var'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='Ownername',
        ),
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Indore', 'Indore'), ('Bhopal', 'Bhopal'), ('Gwalior', 'Gwalior'), ('Jablpur', 'Jablpur')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Listing_type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], default='Sell', max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('4BHK', '4BHK'), ('1BHK', '1BHK'), ('3BHK', '3BHK'), ('2BHK', '2BHK'), ('SingleRoom', 'SingleRoom'), ('Single+Kitchen', 'Single+Kitchen')], default=None, max_length=20),
        ),
    ]
