# Generated by Django 4.1.3 on 2023-09-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0013_remove_detail_email_remove_detail_ownername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='Ownername',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Bhopal', 'Bhopal'), ('Jablpur', 'Jablpur'), ('Gwalior', 'Gwalior'), ('Indore', 'Indore')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Listing_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sell', 'Sell')], default='Sell', max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('3BHK', '3BHK'), ('Single+Kitchen', 'Single+Kitchen'), ('1BHK', '1BHK'), ('4BHK', '4BHK'), ('2BHK', '2BHK'), ('SingleRoom', 'SingleRoom')], default=None, max_length=20),
        ),
    ]
