# Generated by Django 4.1.3 on 2023-09-11 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_door', '0014_detail_email_detail_ownername_alter_detail_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Contactnumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Listing_type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], default='Sell', max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('SingleRoom', 'SingleRoom'), ('1BHK', '1BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('2BHK', '2BHK'), ('Single+Kitchen', 'Single+Kitchen')], default=None, max_length=20),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('room_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_door.detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
