# Generated by Django 4.1.3 on 2023-09-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0016_alter_booking_booking_date_alter_detail_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Jablpur', 'Jablpur'), ('Indore', 'Indore'), ('Gwalior', 'Gwalior'), ('Bhopal', 'Bhopal')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('4BHK', '4BHK'), ('3BHK', '3BHK'), ('2BHK', '2BHK'), ('Single+Kitchen', 'Single+Kitchen'), ('SingleRoom', 'SingleRoom'), ('1BHK', '1BHK')], default=None, max_length=20),
        ),
    ]
