# Generated by Django 4.1.3 on 2023-09-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_door', '0018_booking_email_alter_detail_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='City',
            field=models.CharField(choices=[('Bhopal', 'Bhopal'), ('Indore', 'Indore'), ('Jablpur', 'Jablpur'), ('Gwalior', 'Gwalior')], default='Bhopal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Room_var',
            field=models.CharField(choices=[('4BHK', '4BHK'), ('3BHK', '3BHK'), ('2BHK', '2BHK'), ('Single+Kitchen', 'Single+Kitchen'), ('SingleRoom', 'SingleRoom'), ('1BHK', '1BHK')], default=None, max_length=20),
        ),
    ]
